### ISSUE TITLE
Feature / Suggestion : Product card

### ISSUE THREAD

**Issue by Lewiscowles1986** [Shreerang/Vue-Nuggets#10]
A Core part of e-commerce is selling products. It'd be nice to see a listing product card for core attributes as part of this

**Comment by Shreerang** [comment]
If I have understood this correctly, you are talking about the products (product cards) displayed as part of the search or browse page! If that is correct, then here is some explanation.

I am not sure if I would want to build a product card component! This is very opinionated and each e-commerce site is free to choose it's design for the card. Some choose to be minimalistic, with just the product image and rating and price, while some are more descriptive with a long product name, 2 lines of product description and so on. This is something that **cannot be** generalized and should be open to the interpretation of the brand's design and product teams.

To make life easier for developers and designers alike, I have implemented the Grid component, which will help you define how the search and browse page grid should look like at different break points, but the product card within each of these grid items should a component built by the brand development team.

I will soon be creating a demo site better that the existing one that will showcase these pages as well and not just components! I have realized that people find it difficult to picturize how things will look in real time on an actual e-commerce site! So yes this is in the works too and in the roadmap for 2019! I am going to close this for now, unless you have a different take on this, which actually requires a "reusable" component.

**Comment by Shreerang** [comment]
If by product card you mean PDP, there are few components you will see on every PDP and some of those are already built and ready. These include

1. Quantity Selector
2. Color Picker
3. Size Selector
4. Accordion
5. Grid (for anything else)
6. 2 column split view with one column scrolling and one static (Proposed)

Again a  demo for PDP will soon be coming. I have it ready just not committed yet!

**Comment by Lewiscowles1986** [comment]
I didn't mean a product display page, I meant a card listing element, but it's your project.

**Comment by Shreerang** [comment]
Again, what's a card listing element? Can you provide a reference URL to any site that has it?

**Comment by Lewiscowles1986** [comment]
- https://store.nike.com/gb/en_gb/pw/womens-performance/7ptZpmh?intpromo=WLP-WOMAN%3AP1CS1%3A20190214%3AWMNS%3ASHOPNOW%3AUKEXCEPTIONPW
- https://www.ju-ju-be.com/collections/wallets
- https://europe.ju-ju-be.com/collections/wallets

Every single e-commerce store I've ever used has had product card element in one form or another, and would use something such as grid to layout those cards. Perhaps it's terminology. A card is what lives inside a grid item to use css-grid parlance.
