### ISSUE TITLE
Bug / UI : Alert scroll-jack

### ISSUE THREAD

**Issue by Lewiscowles1986** [Shreerang/Vue-Nuggets#7]
When accessing the alert examples it'd be nice if they were in-line or had fixed position so they did not lose my place on page, or had a mechanism to return me to where I was on page.

**Comment by Shreerang** [comment]
Alert is a component that let's you configure "global" vs "inline" alerts and warnings.

Several times when you have more than one inline errors/warnings sites show a global warning at the very top of the form/page. At this time, the page should scroll to the top or to the "top of form" where the global error is shown. Even in case of inline error, the page should scroll to the form field that is erroneous.

Also in case of server side errors, like API not responding or sending an empty response or an error response that needs to be shown globally, we need a global error that is shown at the top of the page or form and need to scroll the user to the error/warning location.

This is all available in the current Alert component. Demo here - https://ecommerce-vue-nuggets.herokuapp.com/

I am going to close this as "not a defect" unless you have a specific use case that I haven't quite understood.
